version: "3"
services:
  # app:
  #   build: .
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - db
  #   networks: 
  #     - net
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    networks:
      - net
    environment:
      MONGODB_USERNAME: demo
      MONGODB_PASSWORD: demo1234
      MONGODB_DATABASE: tests
    volumes:
      - './containers/mongo:/data/db'
networks:
  net: